### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [JuliaJLee/Forecasting_US_Election_2024#1]
- Overview needs to be more detailed. Similar to the abstract.
- Parquet not used
- Testing needs to be more extensive.
- Add a subtitle with actual results
- Abstract not yet done.
- Figure 1 - Change the class of the date variable to resolve the x-axis issue.
- Methodology - include citations to the pre-req readings to increase your credibilty.
- DATA NOT CITED.
- You don't need to cite both dpylr and tidyverse. Just tidyverse is fine. Otherwise it's turtles all the way down.

**Comment by jjlee-lee** [comment]
Thank you for your feedback! As we completed our paper, we made sure to address all your comments.
