### ISSUE TITLE
Comment By Group 90 (Xiaolu Ji)

### ISSUE THREAD

**Issue by Madelinee221** [JuliaJLee/Forecasting_US_Election_2024#3]
Summary
The paper presents a forecast of the 2024 U.S. Presidential Election, focusing on predicting the percentage of votes for the Democratic presidential candidate, Kamala Harris, using a multiple linear regression model. The analysis draws on data from high-quality pollsters, considering key variables such as the date of data collection and whether the polls are national or state-specific. Statistical techniques, including histograms and box plots, are used to visualize the data. The study is informed by literature such as Blumenthal (2014) and Pasek (2015) to examine how pollster location and timing influence political forecasting.

Strong positive points:
* The use of high-quality pollsters to ensure data reliability.
* Clear and effective visualizations to illustrate key findings.
* Engagement with relevant literature.
* The layout is readable.

Critical improvements needed:
* Abstract: The paper lacks a clear abstract. It’s essential to provide a concise overview of the study, including the objectives, methodology, and key findings.
* Model Detail: The paper’s modeling approach requires more explanation. Clearer documentation of the steps taken, including how key variables like numeric_grade and pct are used in the model, is needed to understand the results.
* Discussion Depth: The discussion is underdeveloped. More detail is needed to interpret the findings, particularly regarding how the polling data might influence Harris’s broader political support.
* Introduction Structure: The introduction would benefit from more context and clearer structure, particularly around the research question and methodology.

Suggestions for improvement:
* Title: Consider crafting a more informative title that highlights the specific focus on Harris’s polling performance across high-quality polls. Including key terms like “high-quality polls” and “performance analysis” could make it more precise. Or you can consider adding a subtitle.
* Prose Clarity: Several sections of the paper, especially the introduction, results, and discussion, would benefit from clearer language and enhanced grammar to improve readability. Expanding on key concepts and smoothing transitions will make the analysis more accessible.
* Data Section: There may be limited exploration of relationships between variables like Harris's percentage of votes and date. Summary statistics for all key variables should also be included, and the discussion may need more depth regarding these relationships. Appendices could be used if the paper becomes too detailed. Overall, more comprehensive analysis and explanation are needed to fully meet the requirements.
* Results Section: Expand the results section by incorporating more comprehensive findings. Additional visualizations or tables should be included to highlight key insights from the data, ensuring that the interpretation of results is well supported.
* Captions: Enhance the captions for graphs and tables so they provide sufficient detail to stand alone. Clear, descriptive captions will help readers understand the visuals without needing to refer back to the text.

Evaluation:
R is appropriately cited: 1/1
Data are appropriately cited: 0/1 
Class paper: 1/1
LLM usage is documented: 1/1
Title: 1.5/2 
Author, date, and repo: 2/2
Abstract: 0/4 
Introduction: 1.5/4 
Estimand: 0/1 
Data: 4/10 
Measurement: 2/4
Model: 1/10 
Results: 3/10 
Discussion: 1/10 
Prose: 1.5/6 
Cross-references: 1/1
Captions: 0.5/2 
Graphs/tables/etc.: 2/4 
Idealized methodology: 4/10 
Idealized survey: 3/4 
Pollster methodology overview and evaluation: 6/10 
Referencing: 2/4 
Commits: 1.5/2
Sketches: 0/2 
Simulation: 2/4 
Tests-simulation: 2/4 
Tests-actual: 2/4
Parquet: 0/1 
Reproducible workflow: 1.5/4 
Miscellaneous: 0/3
Estimated Overall Mark:
49 out of 126

Any other comments:
Consider improving the workflow documentation and adding more testing to ensure the robustness of the analysis.

**Comment by jjlee-lee** [comment]
Thank you for your feedback! As per your suggestions, we added more detail to our model, discussion, introduction, data, and results sections.
