### ISSUE TITLE
Peer Review - Yunkyung Ko (Group 13)

### ISSUE THREAD

**Issue by koyunkyung** [JuliaJLee/Forecasting_US_Election_2024#5]
**Summary**

This paper focuses on figuring out the changes in the vote percentage for Harris over time, across pollsters and states. A multiple linear regression model was used to predict the percentage of votes and the author detected minimal fluctuations in support for Harris.

**Strong positive points**

- Idealized survey systematically made, considering every aspect of effective sampling and survey methods
- Concrete and detailed explanation for each part and step in the Appendix section

**Critical improvements needed** 

In order to make the paper and repo more persuasive and easier for others to engage with, modifications to the README file seems necessary. It might be much better with the ‘overview’ part to include the main results of the analysis/prediction and what kind of methods were used in a more specific way. Also, it would be more effective to introduce files in a more organized and unified form.

Regarding the testing of simulation and analysis data, more extensive range of tests would enhance the validity of the dataset used. For instance, tests for checking whether all observations have the pollster and state information in a ‘character’ format would be recommended. 

In A.1 Pollster Methodology, citing the references for the information that you got about the YouGov polling organization might improve the paper’s credibility. Also, for a more natural flow (prose) of the explanations, I suggest mentioning how YouGov deals with potential problems of stratified sampling before you move on to explaining how YouGov uses weighting to deal with non-response issues. For instance, you could show methods YouGov uses to properly choose the stratification criteria to minimize sampling errors.

**Suggestions for improvement** 

The results of the multiple regression model would be likely to be conveyed in a more accurate and reliable manner with some supplementations. Figure 1 and Figure 2 under the ‘4 Results’ section currently shows numerous scatterplots with no summary lines for explaining the trends for each of them. Rather than this kind of graphical method, I would recommend using other measures such as overlaying multiple line graphs after filtering for several pollsters or states of interest. 

Though the idealized survey seems informative, I recommend some changes in its formatting. In the current state, it feels a bit burdensome for the survey respondent to move to one section after another every time they answer to just one question. Instead, it would make things convenient for the respondent if the sections dividers are replaced by title texts that come before each question so that all the questions show up in a glance. Moreover, rather than placing the survey form link at the very first of the section for explaining idealized pollster methodology, it would be more conversational to put that link wherever your methodology steps talk about the survey conduction.

In order to engage the readers into the paper in the initial stage, a more informative title and subtitle for the paper is recommended. Abstract and introduction to the paper, which plays a similar role, seems to be undone.

**Evaluation** 

- R is appropriately cited: 1/1
- Data are appropriately cited: 0/1 (only the packages and R are on the reference list)
- Class paper: 1/1
- LLM usage is documented: 1/1
- Title: 0/2 (not informative enough, subtitle to show the main results needed)
- Author, date, and repo: 2/2
- Abstract: 0/4 (not done yet)
- Introduction: 0/4 (not done yet)
- Estimand: 0/1 (estimand not stated in the introduction)
- Data: 0/10 (not done yet)
- Measurement: 0/4 (not done yet)
- Model: 2/10 (not fully done yet-only the design..)
- Results: 2/10
- Discussion: 0/10 (not done yet)
- Prose: 2/6 (the flow of the paragraphs seems somewhat awkward and modifications needed)
- Cross-references: 1/1
- Captions: 1/2 (not fully informative in that it doesn’t capture what type of graphical method it is using)
- Graphs/tables/etc: 1/4 (does not serve a clear purpose in that the result still seems ambiguous even after looking at the figures provided)
- Idealized methodology: 10/10
- Idealized survey: 3/4 (great, but might be exceptional with better formatting)
- Pollster methodology overview and evaluation: 8/10 (great, but might be exceptional with a more thorough evaluation of the pollster methodology)
- Referencing: 4/4
- Commits: 2/2
- Sketches: 0/2 (not done yet)
- Simulation: 2/4 (need more of the simulation for each of the analysis conducted)
- Tests-simulation: 2/4 (more extensive range of test required to check the sanity and validity of the dataset)
- Tests-actual: 0/4 (more extensive range of test required to check the sanity and validity of the dataset)
- Parquet: 0/1 (not done yet)
- Reproducible workflow: 4/4
- Miscellaneous: 0/3 (likely to improve much more, but not yet)

**Estimated overall mark**

 49 out of 126.

**Any other comments**

Since the structure and subject encompassing the entire paper are good, it is highly likely to be a good enough academic paper when modifications and revisions are made.

**Comment by jjlee-lee** [comment]
Thank you for your feedback! Your comments helped us organize our repo, consider more extensive data testing, and improve the appendices.
